var DicArray = [];DicArray.push({eng: "kite", trk: "|kaɪt|", ukr: "повітряний змій", snd: "kite.mp3"});
DicArray.push({eng: "cloudy", trk: "|ˈklaʊdi|", ukr: "хмарно", snd: "cloudy.mp3"});
DicArray.push({eng: "old", trk: "|əʊld|", ukr: "старий", snd: "old.mp3"});
DicArray.push({eng: "radio", trk: "|ˈreɪdɪəʊ|", ukr: "радіо", snd: "radio.mp3"});
DicArray.push({eng: "new", trk: "|njuː|", ukr: "новий", snd: "new.mp3"});
DicArray.push({eng: "bike", trk: "|baɪk|", ukr: "велосипед", snd: "bike.mp3"});
DicArray.push({eng: "toys", trk: "|tɔɪz|", ukr: "іграшки", snd: "toys.mp3"});
DicArray.push({eng: "rollerblades", trk: "|ˈrəʊ.lə.bleɪds|", ukr: "ролики", snd: "rollerblades.mp3"});
DicArray.push({eng: "train", trk: "|treɪn|", ukr: "поїзд", snd: "train.mp3"});
DicArray.push({eng: "slow", trk: "|sləʊ|", ukr: "повільний", snd: "slow.mp3"});
DicArray.push({eng: "fast", trk: "|fɑːst|", ukr: "швидкий", snd: "fast.mp3"});
DicArray.push({eng: "winner", trk: "|ˈwɪnə|", ukr: "переможець", snd: "winner.mp3"});
DicArray.push({eng: "prize", trk: "|prʌɪz|", ukr: "приз", snd: "prize.mp3"});
DicArray.push({eng: "feet", trk: "|fiːt|", ukr: "ступня", snd: "feet.mp3"});
DicArray.push({eng: "leg", trk: "|leɡ|", ukr: "нога", snd: "leg.mp3"});
DicArray.push({eng: "body", trk: "|ˈbɒdi|", ukr: "тіло", snd: "body.mp3"});
DicArray.push({eng: "head", trk: "|hed|", ukr: "голова", snd: "head.mp3"});
DicArray.push({eng: "wing", trk: "|wɪŋ|", ukr: "крило", snd: "wing.mp3"});
DicArray.push({eng: "hand", trk: "|hænd|", ukr: "кисть руки", snd: "hand.mp3"});
DicArray.push({eng: "arm", trk: "|ɑːm|", ukr: "рука", snd: "arm.mp3"});
DicArray.push({eng: "ear", trk: "|ɪə|", ukr: "вухо", snd: "ear.mp3"});