var DicArray = []; DicArray.push({eng: "mouth", trk: "|maʊθ|", ukr: "рот", snd: "mouth.mp3"});
DicArray.push({eng: "nose", trk: "|nəʊz|", ukr: "ніс", snd: "nose.mp3"});
DicArray.push({eng: "eye", trk: "|aɪ|", ukr: "око", snd: "eye.mp3"});
DicArray.push({eng: "butterfly", trk: "|ˈbʌtərflaɪ|", ukr: "метелик", snd: "butterfly.mp3"});
DicArray.push({eng: "hair", trk: "|heə|", ukr: "волосся", snd: "hair.mp3"});
DicArray.push({eng: "hair slide", trk: "|heə slʌɪd|", ukr: "заколка", snd: "hair slide.mp3"});
DicArray.push({eng: "funny", trk: "|ˈfʌni|", ukr: "смішний", snd: "funny.mp3"});
DicArray.push({eng: "long", trk: "|ˈlɒŋ|", ukr: "довго", snd: "long.mp3"});
DicArray.push({eng: "short", trk: "|ʃɔːt|", ukr: "короткий", snd: "short.mp3"});
DicArray.push({eng: "strong", trk: "|strɒŋ|", ukr: "сильний", snd: "strong.mp3"});
DicArray.push({eng: "trunk", trk: "|trʌŋk|", ukr: "хобот", snd: "trunk.mp3"});
DicArray.push({eng: "star", trk: "|stɑː|", ukr: "зірка", snd: "star.mp3"});
DicArray.push({eng: "house", trk: "|haʊs|", ukr: "будинок", snd: "house.mp3"});
DicArray.push({eng: "swimming pool", trk: "|ˈswɪmɪŋ puːl|", ukr: "басейн", snd: "swimming pool.mp3"});
DicArray.push({eng: "park", trk: "|pɑːk|", ukr: "парк", snd: "park.mp3"});
DicArray.push({eng: "river", trk: "|ˈrɪvə|", ukr: "річка", snd: "river.mp3"});
DicArray.push({eng: "tree", trk: "|triː|", ukr: "дерево", snd: "tree.mp3"});
DicArray.push({eng: "playground", trk: "|ˈpleɪɡraʊnd|", ukr: "дитячий майданчик", snd: "playground.mp3"});
DicArray.push({eng: "children", trk: "|ˈtʃɪldrən|", ukr: "діти", snd: "children.mp3"});
DicArray.push({eng: "town", trk: "|taʊn|", ukr: "невелике місто", snd: "town.mp3"});