var DicArray = []; DicArray.push({eng: "hot", trk: "|hɒt|", ukr: "гарячий", snd: "hot.mp3"});
DicArray.push({eng: "treehouse", trk: "|triː haʊs|", ukr: "будинок на дереві", snd: "treehouse.mp3"});
DicArray.push({eng: "shop", trk: "|ʃɒp|", ukr: "магазин", snd: "shop.mp3"});
DicArray.push({eng: "swing", trk: "|swɪŋ|", ukr: "гойдалка", snd: "swing.mp3"});
DicArray.push({eng: "slide", trk: "|slʌɪd|", ukr: "гірка", snd: "slide.mp3"});
DicArray.push({eng: "climbing frame", trk: "|ˈklʌɪmɪŋ freɪm|", ukr: "конструкція для лазання", snd: "climbing frame.mp3"});
DicArray.push({eng: "bus", trk: "|bʌs|", ukr: "автобус", snd: "bus.mp3"});
DicArray.push({eng: "where", trk: "|wɛː|", ukr: "де, куди", snd: "where.mp3"});
DicArray.push({eng: "in", trk: "|ɪn|", ukr: "у, в", snd: "in.mp3"});
DicArray.push({eng: "on", trk: "|ɒn|", ukr: "на, по", snd: "on.mp3"});
DicArray.push({eng: "under", trk: "|ˈʌndə|", ukr: "під", snd: "under.mp3"});
DicArray.push({eng: "next to", trk: "|nekst tə|", ukr: "поруч з", snd: "next to.mp3"});
DicArray.push({eng: "sing", trk: "|sɪŋ|", ukr: "співати", snd: "sing.mp3"});
DicArray.push({eng: "jump", trk: "|dʒʌmp|", ukr: "стрибати", snd: "jump.mp3"});
DicArray.push({eng: "high", trk: "|haɪ|", ukr: "високий", snd: "high.mp3"});
DicArray.push({eng: "fast", trk: "|fɑːst|", ukr: "швидкий", snd: "fast.mp3"});
DicArray.push({eng: "listen", trk: "|ˈlɪs(ə)n|", ukr: "слухати", snd: "listen.mp3"});
DicArray.push({eng: "ride", trk: "|raɪd|", ukr: "їздити", snd: "ride.mp3"});
DicArray.push({eng: "swim", trk: "|swɪm|", ukr: "плавати", snd: "swim.mp3"});
DicArray.push({eng: "climb", trk: "|klʌɪm|", ukr: "вилазити на", snd: "climb.mp3"});
DicArray.push({eng: "play the guitar", trk: "|ˈpleɪ ðə ɡɪˈtɑː|", ukr: "грати на гітарі", snd: "play the guitar.mp3"});
DicArray.push({eng: "can", trk: "kæn", ukr: "могти", snd: "can.mp3"});