var DicArray = []; DicArray.push({eng: "skip", trk: "|skɪp|", ukr: "перестрибувати", snd: "skip.mp3"});
DicArray.push({eng: "rollerblade", trk: "|ˈrəʊ.lə.bleɪd|", ukr: "ролики", snd: "rollerblade.mp3"});
DicArray.push({eng: "fly", trk: "|flaɪ|", ukr: "літати", snd: "fly.mp3"});
DicArray.push({eng: "do a handstand", trk: "|duː eɪ ˈhændstænd|", ukr: "стояти на руках", snd: "do a handstand.mp3"});
DicArray.push({eng: "walk", trk: "|wɔːk|", ukr: "іти", snd: "walk.mp3"});
DicArray.push({eng: "run", trk: "|rʌn|", ukr: "бігти", snd: "run.mp3"});
DicArray.push({eng: "carry", trk: "|ˈkari|", ukr: "нести", snd: "carry.mp3"});
DicArray.push({eng: "mobile phone", trk: "|ˈmoʊbl foʊn|", ukr: "мобільний телефон", snd: "mobile phone.mp3"});
DicArray.push({eng: "desk", trk: "|desk|", ukr: "письмовий стіл", snd: "desk.mp3"});
DicArray.push({eng: "cupboard", trk: "|ˈkʌbəd|", ukr: "шафа", snd: "cupboard.mp3"});
DicArray.push({eng: "computer", trk: "|kəmˈpjuːtə|", ukr: "комп'ютер", snd: "computer.mp3"});
DicArray.push({eng: "bookcase", trk: "|ˈbʊkkeɪs|", ukr: "книжкова шафа", snd: "bookcase.mp3"});
DicArray.push({eng: "table", trk: "|ˈteɪbl|", ukr: "стіл", snd: "table.mp3"});
DicArray.push({eng: "bed", trk: "|bed|", ukr: "ліжко", snd: "bed.mp3"});
DicArray.push({eng: "breakfast", trk: "|ˈbrɛkfəst|", ukr: "сніданок", snd: "breakfast.mp3"});
DicArray.push({eng: "hungry", trk: "|ˈhʌŋɡri|", ukr: "голодний", snd: "hungry.mp3"});
DicArray.push({eng: "bread", trk: "|brɛd|", ukr: "хліб", snd: "bread.mp3"});
DicArray.push({eng: "honey", trk: "|ˈhʌni|", ukr: "мед", snd: "honey.mp3"});
DicArray.push({eng: "milk", trk: "|mɪlk|", ukr: "молоко", snd: "milk.mp3"});
DicArray.push({eng: "egg", trk: "|eɡ|", ukr: "яйце", snd: "egg.mp3"});
DicArray.push({eng: "orange", trk: "|ˈɔːrɪndʒ|", ukr: "апельсин", snd: "orange.mp3"});