var DicArray = []; DicArray.push({eng: "fish", trk: "|fɪʃ|", ukr: "риба", snd: "fish.mp3"});
DicArray.push({eng: "lunch", trk: "|lʌntʃ|", ukr: "обід", snd: "lunch.mp3"});
DicArray.push({eng: "pizza", trk: "|ˈpiːtsə|", ukr: "піца", snd: "pizza.mp3"});
DicArray.push({eng: "soup", trk: "|suːp|", ukr: "суп", snd: "soup.mp3"});
DicArray.push({eng: "chicken", trk: "|ˈtʃɪkɪn|", ukr: "курка", snd: "chicken.mp3"});
DicArray.push({eng: "salad", trk: "|ˈsaləd|", ukr: "салат", snd: "salad.mp3"});
DicArray.push({eng: "get up", trk: "|ˈɡet ʌp|", ukr: "вставати", snd: "get up.mp3"});
DicArray.push({eng: "seven o'clock", trk: "|ˈsevn əˈklɒk|", ukr: "сім годин", snd: "seven o'clock.mp3"});
DicArray.push({eng: "have breakfast", trk: "|hæv ˈbrɛkfəst|", ukr: "снідати", snd: "have breakfast.mp3"});
DicArray.push({eng: "clean my teeth", trk: "|kliːn maɪ tuːθ|", ukr: "чистити зуби", snd: "clean my teeth.mp3"});
DicArray.push({eng: "go to school", trk: "|ɡəʊ tuː skuːl|", ukr: "іти до школи", snd: "go to school.mp3"});
DicArray.push({eng: "Monday", trk: "|ˈmʌndeɪ|", ukr: "понеділок", snd: "Monday.mp3"});
DicArray.push({eng: "Tuesday", trk: "|ˈtjuːzdeɪ|", ukr: "вівторок", snd: "Tuesday.mp3"});
DicArray.push({eng: "Wednesday", trk: "|ˈwɛnzdeɪ|", ukr: "середа", snd: "Wednesday.mp3"});
DicArray.push({eng: "Thursday", trk: "|ˈθəːzdeɪ|", ukr: "четвер", snd: "Thursday.mp3"});
DicArray.push({eng: "Friday", trk: "|ˈfrʌɪdeɪ|", ukr: "п'ятниця", snd: "Friday.mp3"});
DicArray.push({eng: "Saturday", trk: "|ˈsatədeɪ|", ukr: "субота", snd: "Saturday.mp3"});
DicArray.push({eng: "Sunday", trk: "|ˈsʌndeɪ|", ukr: "неділя", snd: "Sunday.mp3"});
DicArray.push({eng: "help", trk: "|help|", ukr: "допомогти", snd: "help.mp3"});
DicArray.push({eng: "people", trk: "|ˈpiːpl|", ukr: "люди", snd: "people.mp3"});
DicArray.push({eng: "police officer", trk: "|pəˈliːs ˈɒfɪsə|", ukr: "офіцер поліції", snd: "police officer.mp3"});
DicArray.push({eng: "fireman", trk: "|ˈfʌɪəmən|", ukr: "пожежник", snd: "fireman.mp3"});
DicArray.push({eng: "visit", trk: "|ˈvɪzɪt|", ukr: "візит", snd: "visit.mp3"});
DicArray.push({eng: "do my homework", trk: "|duː maɪ ˈhəʊmwəːk|", ukr: "робити моє домашнє завдання", snd: "do my homework.mp3"});
DicArray.push({eng: "paint", trk: "|peɪnt|", ukr: "фарбувати, малювати", snd: "paint.mp3"});
DicArray.push({eng: "hide", trk: "|haɪd|", ukr: "ховати", snd: "hide.mp3"});
DicArray.push({eng: "now", trk: "|naʊ|", ukr: "зараз", snd: "now.mp3"});
DicArray.push({eng: "Easter", trk: "|ˈiːstə|", ukr: "Великдень", snd: "Easter.mp3"});
DicArray.push({eng: "throw", trk: "|θrəʊ|", ukr: "кинути", snd: "throw.mp3"});
DicArray.push({eng: "streamers", trk: "|ˈstriːməz|", ukr: "серпантин", snd: "streamers.mp3"});
DicArray.push({eng: "mask", trk: "|mɑːsk|", ukr: "маска", snd: "mask.mp3"});
DicArray.push({eng: "laugh", trk: "|lɑːf|", ukr: "сміятися", snd: "laugh.mp3"});
DicArray.push({eng: "put on", trk: "|ˈpʊt ɒn|", ukr: "одягнути", snd: "put on.mp3"});
DicArray.push({eng: "Have a good day!", trk: "|hæv e ɡʊd deɪ|", ukr: "Гарного дня!", snd: "Have a good day!.mp3"});
DicArray.push({eng: "Well done!", trk: "|wel dʌn|", ukr: "Чудова робота!", snd: "Well done!.mp3"});
DicArray.push({eng: "Don't mention it!", trk: "|dont ˈmenʃn it|", ukr: "Нема за що! (`Не згадуй це!`)", snd: "Don't mention it!.mp3"});
DicArray.push({eng: "Help yourself!", trk: "|help jɔːˈsɛlf|", ukr: "Пригощайтеся!", snd: "Help yourself!.mp3"});
DicArray.push({eng: "It's my pleasure!", trk: "|Its maɪ ˈplɛʒə|", ukr: "Мені приємно!", snd: "It's my pleasure!.mp3"});
DicArray.push({eng: "naughty", trk: "|ˈnɔːti|", ukr: "неслухняний", snd: "naughty.mp3"});
DicArray.push({eng: "How about you?", trk: "|ˈhaʊ əˈbaʊt ju?|", ukr: "Як щодо тебе?", snd: "How about you7.mp3"});
DicArray.push({eng: "Here you are.", trk: "|hɪə ju ɑː|", ukr: "Ось візьми.", snd: "Here you are.mp3"});