var DicArray = []; DicArray.push({eng: "play", trk: "|ˈpleɪ|", ukr: "грати", snd: "play.mp3"});
DicArray.push({eng: "read", trk: "|riːd|", ukr: "читати", snd: "read.mp3"});
DicArray.push({eng: "sleep", trk: "|sliːp|", ukr: "спати", snd: "sleep.mp3"});
DicArray.push({eng: "hide", trk: "|haɪd|", ukr: "приховати", snd: "hide.mp3"});
DicArray.push({eng: "water pistol", trk: "|ˈwɔːtə ˈpɪst(ə)l|", ukr: "водяний пістолет", snd: "water pistol.mp3"});
DicArray.push({eng: "come", trk: "|kʌm|", ukr: "приходити", snd: "come.mp3"});
DicArray.push({eng: "have a shower", trk: "|hæv æ ˈʃaʊə|", ukr: "приймати душ", snd: "have a shower.mp3"});
DicArray.push({eng: "trousers", trk: "|ˈtraʊzəz|", ukr: "штани", snd: "trousers.mp3"});
DicArray.push({eng: "T-shirt", trk: "|ˈtiːʃəːt|", ukr: "футболка", snd: "t-shirt.mp3"});
DicArray.push({eng: "shoes", trk: "|ʃuːz|", ukr: "взуття", snd: "shoes.mp3"});
DicArray.push({eng: "skirt", trk: "|skəːt|", ukr: "спідниця", snd: "skirt.mp3"});
DicArray.push({eng: "dress", trk: "|drɛs|", ukr: "плаття", snd: "dress.mp3"});
DicArray.push({eng: "sweater", trk: "|ˈswɛtə|", ukr: "светр", snd: "sweater.mp3"});
DicArray.push({eng: "basketball", trk: "|ˈbɑːskɪtbɔːl|", ukr: "баскетбол", snd: "basketball.mp3"});
DicArray.push({eng: "volleyball", trk: "|ˈvɒlɪbɔːl|", ukr: "волейбол", snd: "volleyball.mp3"});
DicArray.push({eng: "football", trk: "|ˈfʊtbɔːl|", ukr: "футбол", snd: "football.mp3"});
DicArray.push({eng: "tennis", trk: "|ˈtɛnɪs|", ukr: "теніс", snd: "tennis.mp3"});
DicArray.push({eng: "idea", trk: "|aɪˈdɪə|", ukr: "ідея", snd: "idea.mp3"});
DicArray.push({eng: "tired", trk: "|tʌɪəd|", ukr: "втомлений", snd: "tired.mp3"});
DicArray.push({eng: "dream", trk: "|driːm|", ukr: "мріяти", snd: "dream.mp3"});
DicArray.push({eng: "noise", trk: "|nɔɪz|", ukr: "шум", snd: "noise.mp3"});
DicArray.push({eng: "eat", trk: "|iːt|", ukr: "їсти", snd: "eat.mp3"});
DicArray.push({eng: "drink", trk: "|drɪŋk|", ukr: "пити", snd: "drink.mp3"});
DicArray.push({eng: "upstairs", trk: "|ˌʌpˈsteəz|", ukr: "нагорі", snd: "upstairs.mp3"});
DicArray.push({eng: "roar", trk: "|rɔː|", ukr: "ричати, рев", snd: "roar.mp3"});
DicArray.push({eng: "snore", trk: "|snɔː|", ukr: "хропіти", snd: "snore.mp3"});
DicArray.push({eng: "giant", trk: "|ˈdʒʌɪənt|", ukr: "гігант", snd: "giant.mp3"});
DicArray.push({eng: "hear", trk: "|hɪə|", ukr: "чути", snd: "hear.mp3"});
DicArray.push({eng: "living room", trk: "|ˈlɪvɪŋ ruːm|", ukr: "вітальня", snd: "living room.mp3"});
DicArray.push({eng: "bathroom", trk: "|ˈbɑːθruːm|", ukr: "ванна кімната", snd: "bathroom.mp3"});
DicArray.push({eng: "kitchen", trk: "|ˈkɪtʃɪn|", ukr: "кухня", snd: "kitchen.mp3"});
DicArray.push({eng: "bedroom", trk: "|ˈbɛdruːm|", ukr: "спальня", snd: "bedroom.mp3"});
DicArray.push({eng: "ghost", trk: "|ɡəʊst|", ukr: "привид", snd: "ghost.mp3"});