var DicArray = []; DicArray.push({eng: "toast", trk: "|təʊst|", ukr: "тост", snd: "toast.mp3"});
DicArray.push({eng: "Sweet dreams!", trk: "|swiːt swiːt|", ukr: "Солодких снів!", snd: "Sweet dreams.mp3"});
DicArray.push({eng: "crab", trk: "|kræb|", ukr: "краб", snd: "crab.mp3"});
DicArray.push({eng: "raining", trk: "|ˈreɪnɪŋ|", ukr: "дощ", snd: "raining.mp3"});
DicArray.push({eng: "dolphin", trk: "|ˈdɒlfɪn|", ukr: "дельфін", snd: "dolphin.mp3"});
DicArray.push({eng: "turtle", trk: "|ˈtɜːrtl|", ukr: "черепаха", snd: "turtle.mp3"});
DicArray.push({eng: "a man", trk: "|mæn|", ukr: "чоловік", snd: "man.mp3"});
DicArray.push({eng: "men", trk: "|men|", ukr: "чоловіки", snd: "men.mp3"});
DicArray.push({eng: "feed", trk: "|fiːd|", ukr: "годувати", snd: "feed.mp3"});
DicArray.push({eng: "a woman", trk: "|ˈwʊmən|", ukr: "жінка", snd: "woman.mp3"});
DicArray.push({eng: "women", trk: "|women|", ukr: "жінки", snd: "women.mp3"});
DicArray.push({eng: "tall", trk: "|tɔːl|", ukr: "високий", snd: "tall.mp3"});
DicArray.push({eng: "shark", trk: "|ʃɑːk|", ukr: "акула", snd: "shark.mp3"});
DicArray.push({eng: "tooth", trk: "|tuːθ|", ukr: "зуб", snd: "tooth.mp3"});
DicArray.push({eng: "teeth", trk: "|tiːθ|", ukr: "зуби", snd: "teeth.mp3"});
DicArray.push({eng: "fox", trk: "|fɒks|", ukr: "лисиця", snd: "fox.mp3"});
DicArray.push({eng: "bus", trk: "|bʌs|", ukr: "автобус", snd: "bus.mp3"});
DicArray.push({eng: "dress", trk: "|drɛs|", ukr: "плаття", snd: "dress.mp3"});
DicArray.push({eng: "watch", trk: "|wɒtʃ|", ukr: "годинник", snd: "watch.mp3"});
DicArray.push({eng: "baby", trk: "|ˈbeɪbi|", ukr: "дитина", snd: "baby.mp3"});
DicArray.push({eng: "family", trk: "|ˈfamɪli|", ukr: "сім'я", snd: "family.mp3"});
DicArray.push({eng: "spy", trk: "|ˈspaɪ|", ukr: "шпигун", snd: "spy.mp3"});
DicArray.push({eng: "child", trk: "|tʃʌɪld|", ukr: "дитина", snd: "child.mp3"});
DicArray.push({eng: "children", trk: "|ˈtʃɪldrən|", ukr: "діти", snd: "children.mp3"});
DicArray.push({eng: "foot", trk: "|fʊt|", ukr: "стопа", snd: "foot.mp3"});
DicArray.push({eng: "feet", trk: "|fiːt|", ukr: "ступні", snd: "feet.mp3"});
//(Lesson 1)
DicArray.push({eng: "Africa", trk: "|ˈafrɪkə|", ukr: "Африка ", snd: "Africa.mp3"});
DicArray.push({eng: "airport", trk: "|ˈɛːpɔːt|", ukr: "аeропорт", snd: "airport.mp3"});
DicArray.push({eng: "aunt", trk: "|ɑːnt|", ukr: "тітка", snd: "aunt.mp3"});
DicArray.push({eng: "uncle", trk: "|ˈʌŋkl|", ukr: "дядько", snd: "uncle.mp3"});
DicArray.push({eng: "cousin", trk: "|ˈkʌzn|", ukr: "кузен, кузина", snd: "cousin.mp3"});
DicArray.push({eng: "holiday", trk: "|ˈhɒlɪdeɪ|", ukr: "канікули, свято, вихідний", snd: "holiday.mp3"});
//(Lesson 2)
DicArray.push({eng: "shy", trk: "|ʃaɪ|", ukr: "сором'язливий", snd: "shy.mp3"});
DicArray.push({eng: "England", trk: "|ˈɪŋɡlənd|", ukr: "Англія", snd: "England.mp3"});
DicArray.push({eng: "spaghetti", trk: "|spəˈɡɛti|", ukr: "спагетті", snd: "spaghetti.mp3"});
DicArray.push({eng: "cheese", trk: "|tʃiːz|", ukr: "сир", snd: "cheese.mp3"});
DicArray.push({eng: "ice cream", trk: "|aɪs kriːm|", ukr: "морозиво", snd: "ice cream.mp3"});
DicArray.push({eng: "dinner", trk: "|ˈdɪnə|", ukr: "вечеря", snd: "dinner.mp3"});