var DicArray = []; DicArray.push({eng: "map", trk: "|mæp|", ukr: "карта", snd: "map.mp3"});
DicArray.push({eng: "sunglasses", trk: "|ˈsʌnɡlɑːsɪz|", ukr: "сонцезахисні окуляри", snd: "sunglasses.mp3"});
DicArray.push({eng: "shirt", trk: "|ʃəːt|", ukr: "сорочка", snd: "shirt.mp3"});
DicArray.push({eng: "swimsuit", trk: "|ˈswɪmsuːt|", ukr: "купальник", snd: "swimsuit.mp3"});
DicArray.push({eng: "smile", trk: "|smʌɪl|", ukr: "усмішка", snd: "smile.mp3"});
DicArray.push({eng: "passport", trk: "|ˈpɑːspɔːt|", ukr: "паспорт", snd: "passport.mp3"});
DicArray.push({eng: "ticket", trk: "|ˈtɪkɪt|", ukr: "квиток", snd: "ticket.mp3"});
DicArray.push({eng: "plane", trk: "|pleɪn|", ukr: "літак", snd: "plane.mp3"});
DicArray.push({eng: "money", trk: "|ˈmʌni|", ukr: "гроші", snd: "money.mp3"});
DicArray.push({eng: "suitcase", trk: "|ˈsuːtkeɪs|", ukr: "валіза", snd: "suitcase.mp3"});
DicArray.push({eng: "taxi", trk: "|ˈtæksi|", ukr: "таксі", snd: "taxi.mp3"});
DicArray.push({eng: "Maths", trk: "|maθs|", ukr: "Математика", snd: "maths.mp3"});
DicArray.push({eng: "English", trk: "|ˈɪŋɡlɪʃ|", ukr: "Англійська", snd: "english.mp3"});
DicArray.push({eng: "History", trk: "|ˈhɪst(ə)ri|", ukr: "Історія", snd: "history.mp3"});
DicArray.push({eng: "Art", trk: "|Art|", ukr: "мистецтво", snd: "art.mp3"});
DicArray.push({eng: "dinosaur", trk: "|ˈdʌɪnəsɔː|", ukr: "динозавр", snd: "dinosaur.mp3"});
DicArray.push({eng: "PE", trk: "|ˌpiːˈiː|", ukr: "фізична культура.", snd: "pe.mp3"});
DicArray.push({eng: "morning", trk: "|morning|", ukr: "ранок", snd: "morning.mp3"});
DicArray.push({eng: "letter", trk: "|ˈlɛtə|", ukr: "лист", snd: "letter.mp3"});
DicArray.push({eng: "postcard", trk: "|ˈpoʊstkɑːrd|", ukr: "листівка", snd: "postcard.mp3"});
DicArray.push({eng: "parcel", trk: "|ˈpɑːrsl|", ukr: "посилка", snd: "parcel.mp3"});
DicArray.push({eng: "afternoon", trk: "|ɑːftəˈnuːn|", ukr: "вдень", snd: "afternoon.mp3"});
DicArray.push({eng: "evening", trk: "|ˈiːvnɪŋ|", ukr: "вечір", snd: "evening.mp3"});
DicArray.push({eng: "watch TV", trk: "|wɒtʃ ˌtiːˈviː|", ukr: "дивитись телевізор", snd: "watch TV.mp3"});
