DicArray.push({eng: "pen", trk: "|pen|", ukr: "ручка", snd: "pen.mp3"});
DicArray.push({eng: "rubber", trk: "|ˈrʌbər|", ukr: "гума", snd: "rubber.mp3"});
DicArray.push({eng: "book", trk: "|bʊk|", ukr: "книга", snd: "book.mp3"});
DicArray.push({eng: "spell", trk: "|spel|", ukr: "проголошувати", snd: "spell.mp3"});
DicArray.push({eng: "chair", trk: "|tʃeə|", ukr: "стілець", snd: "chair.mp3"});
DicArray.push({eng: "write", trk: "|raɪt|", ukr: "писати", snd: "write.mp3"});
DicArray.push({eng: "board", trk: "|bɔːrd|", ukr: "дошка", snd: "board.mp3"});
DicArray.push({eng: "be quite", trk: "|bi kwaɪt|", ukr: "бути тихим", snd: "be quite.mp3"});
DicArray.push({eng: "car", trk: "|kɑːr|", ukr: "автомобіль", snd: "car.mp3"});
DicArray.push({eng: "ball", trk: "|bɔːl|", ukr: "м'яч", snd: "ball.mp3"});
DicArray.push({eng: "doll", trk: "|doll|", ukr: "лялька", snd: "doll.mp3"});
DicArray.push({eng: "stickers", trk: "|ˈstɪkəz|", ukr: "наклейки", snd: "stickers.mp3"});
DicArray.push({eng: "crayon", trk: "|ˈkreɪən|", ukr: "олівець", snd: "crayon.mp3"});
DicArray.push({eng: "card", trk: "|kɑːrd|", ukr: "картка", snd: "card.mp3"});
DicArray.push({eng: "robot", trk: "|ˈrəʊbɒt|", ukr: "робот", snd: "robot.mp3"});
DicArray.push({eng: "birthday", trk: "|ˈbɜːθdeɪ|", ukr: "день народження", snd: "birthday.mp3"});
DicArray.push({eng: "cake", trk: "|keɪk|", ukr: "торт", snd: "cake.mp3"});
DicArray.push({eng: "present", trk: "|ˈpreznt|", ukr: "подарунок", snd: "present.mp3"});
DicArray.push({eng: "watch", trk: "|wɑːtʃ|", ukr: "годинник", snd: "watch.mp3"});
DicArray.push({eng: "frog", trk: "|frɒɡ|", ukr: "жаба", snd: "frog.mp3"});
DicArray.push({eng: "teacher", trk: "|ˈtiːtʃə|", ukr: "учитель", snd: "teacher.mp3"});
DicArray.push({eng: "close", trk: "|kloʊz|", ukr: "закрити", snd: "close.mp3"});
DicArray.push({eng: "door", trk: "|dɔː|", ukr: "двері", snd: "door.mp3"});
DicArray.push({eng: "window", trk: "|ˈwɪndəʊ|", ukr: "вікно", snd: "window.mp3"});
DicArray.push({eng: "stand up", trk: "|ˈstænd ʌp|", ukr: "вставати", snd: "stand up.mp3"});
DicArray.push({eng: "open", trk: "|ˈəʊpən|", ukr: "відкривати", snd: "open.mp3"});
DicArray.push({eng: "sit down", trk: "|sɪt daʊn|", ukr: "сідати", snd: "sit down.mp3"});
DicArray.push({eng: "sunny", trk: "|ˈsʌnɪ|", ukr: "сонячно", snd: "sunny.mp3"});
DicArray.push({eng: "family", trk: "|ˈfæməlɪ|", ukr: "сім'я", snd: "family.mp3"});
DicArray.push({eng: "mum", trk: "|mʌm|", ukr: "мама", snd: "mum.mp3"});
DicArray.push({eng: "dad", trk: "|dæd|", ukr: "тато", snd: "dad.mp3"});
DicArray.push({eng: "brother", trk: "|ˈbrʌðə|", ukr: "брат", snd: "brother.mp3"});
DicArray.push({eng: "sister", trk: "|ˈsɪstə|", ukr: "сестра", snd: "sister.mp3"});
DicArray.push({eng: "grandpa", trk: "|ˈɡræn(d)pɑː|", ukr: "дідусь", snd: "grandpa.mp3"});
DicArray.push({eng: "baby", trk: "|ˈbeɪbɪ|", ukr: "дитина", snd: "baby.mp3"});
DicArray.push({eng: "boy", trk: "|ˌbɔɪ|", ukr: "хлопчик", snd: "boy.mp3"});
DicArray.push({eng: "girl", trk: "|ɡɜːl|", ukr: "дівчина", snd: "girl.mp3"});
DicArray.push({eng: "grandma", trk: "|бабуся|", ukr: "бабуся", snd: "grandma.mp3"});
DicArray.push({eng: "friend", trk: "|frend|", ukr: "друг", snd: "friend.mp3"});
DicArray.push({eng: "cowboy", trk: "|ˈkaʊbɔɪ|", ukr: "ковбой", snd: "cowboy.mp3"});
DicArray.push({eng: "box", trk: "|bɒks|", ukr: "коробка", snd: "box.mp3"});
DicArray.push({eng: "clothes", trk: "|kləʊ(ð)z|", ukr: "одяг", snd: "clothes.mp3"});
DicArray.push({eng: "spy", trk: "|spaɪ|", ukr: "шпигун", snd: "spy.mp3"});
DicArray.push({eng: "dancer", trk: "|ˈdɑːnsə|", ukr: "танцівниця", snd: "dancer.mp3"});
DicArray.push({eng: "pirate", trk: "|ˈpaɪrət|", ukr: "пірат", snd: "pirate.mp3"});
DicArray.push({eng: "clown", trk: "|klaʊn|", ukr: "клоун", snd: "clown.mp3"});
DicArray.push({eng: "king", trk: "|kɪŋ|", ukr: "король", snd: "king.mp3"});
DicArray.push({eng: "crown", trk: "|kraʊn|", ukr: "корона", snd: "crown.mp3"});
